name: Build CRM Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Clear NuGet cache
        run: nuget locals all -clear

      - name: Restore Packages
        run: nuget restore CRM.RCRC.slnx

      - name: Build
        run: msbuild CRM.RCRC.slnx /t:Clean,Build /p:Configuration=Release /p:Platform="Any CPU"

      - name: Show release output files
        if: always()
        run: dir CRM.RCRC\bin\Release

      - name: Upload Plugin DLL
        uses: actions/upload-artifact@v4
        with:
          name: CRM-RCRC-plugin-build
          path: |
            CRM.RCRC\bin\Release\CRM.RCRC.dll
            CRM.RCRC\bin\Release\CRM.RCRC.pdb
